### ISSUE TITLE
Diode silkscreen orientation confuses automation

### ISSUE THREAD

**Issue by tobozo** [frntc/SIDKick-pico#2]
Hi and thanks for this project :+1: 

I used the [provided link](https://www.pcbway.com/project/shareproject/W160781ASB18_Gerber_1790f9c8.html) to make an order at PCBWay and got a feedback question from them, asking confirmation about the orientation of a diode.

I compared their picture with the one in the `Images/` folder of this repository and figured their system got it inverted.

#### Picture from PCBWay assembly line, where the diode is mounted with the wrong orientation:

![image](https://github.com/frntc/SIDKick-pico/assets/1893754/4eff5ab3-eb44-43b6-bca2-3fe03c6c4615)

#### Picture from this repository where the diode has the right orientation:

![image](https://github.com/frntc/SIDKick-pico/assets/1893754/afcafd13-2d86-4758-bfe3-1ddc7931c6c8)

Based on a default footprint, it looks like the label + symbol have been inverted, but not the silkscreen lines surrounding the diode placeholder.

![image](https://github.com/frntc/SIDKick-pico/assets/1893754/3ecb4321-d480-4f0e-a951-4bc638edd048)

#### Is it safe to assume silkscreen should look like this instead?

![image](https://github.com/frntc/SIDKick-pico/assets/1893754/7b6c8620-5302-4901-9ee0-53c6838782ca)

**Comment by frntc** [comment]
Hi,

PCBWay asked me the exactly same thing when I placed the order of a test-batch. I explicitly asked them to not forget about the correct placement, but ...

Put short:
- the orientation on my photos is correct
- feel free to refer to my PCBWay order T-B19W160781A (and related conversation about placement)

Hope this helps!

**Comment by tobozo** [comment]
thanks for confirming
