### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by retrogralnia** [frntc/SIDKick-pico#20]
I order PCB preassembled and have some problems: PWM sound is almost inaudible and SYS command is not working.  Got any tips?

**Comment by frntc** [comment]
PWM output has a lower amplitude, but it shouldn't be "almost inaudible". 

Maybe best is to start with the SYS-problem. Have you checked all solder connections, or tried another PCB from your batch? What C64 are you using? Can you run a monitor (and what does D D400 output)?

**Comment by retrogralnia** [comment]
Oh... god.... It was common soldering mishab... Sorry!

**Comment by retrogralnia** [comment]
Oh... god.... It was common soldering mishab... Sorry!
