### ISSUE TITLE
Clarification on license please.

### ISSUE THREAD

**Issue by dabonetn** [frntc/SIDKick-pico#30]
What's you position on reselling spare pcbs for cost + shipping?

I ordered extra bare boards from PCBWay, and was wondering if I could offer them up for the 0.66 each + the cost of a stamp and envelope?

**Comment by frntc** [comment]
Thanks for asking -- dissemination of the project in this way is greatly appreciated! The license only forbids commercial intents (e.g. selling not just spare units on ebay, high volumes/prices, offer from persons who run shops).

**Comment by youngd24** [comment]
Another question related to this, I ordered 10 boards and used a couple myself, was thinking of making up a few kits and a few completed ones to sell at VCFMW, is that ok within the license? Kits for like $10-$12, assembled for $20-$25.
