### ISSUE TITLE
Add Firmware descriptions please.

### ISSUE THREAD

**Issue by dabonetn** [frntc/SIDKick-pico#34]
I've built a couple and downloaded the latest release, but the only thing in the release is 9 firmware files.

They mention LED and RGB, and PWM and Dac, but there's no instructions on what does what.

Any chance of adding a readme to the releases for clarification?

(I'm assuming you are using attaching a RGB led or regular LED somewhere, but I don't see that on the main page.)

**Comment by marty41** [comment]
There is a RGB LEDs on some of the Chinese Picos. To activate it you can use the firmware with the LED in the name. 
Also see: https://www.forum64.de/index.php?thread/140808-projektvorstellung-sidkick-pico/&postID=2088499#post2088499
