### ISSUE TITLE
Serious problem

### ISSUE THREAD

**Issue by Braincell1973** [frntc/SIDKick-pico#4]
I'm having corrupted sound in....

Shadowfire (starts ok then sounds like it loses a channel )
Enigma force
Mutants

Firmware 0.12
Tried in both 6581 and 8380 with and without digi

Files from oneload64,v4

Using pwm only

Other files like fist2, light force, zoids, scarabaeus play fine

Single sid configuration using a KFF cartridge

**Comment by marty41** [comment]
Maybe it would be a good idea to add what firmware you are using and in what mode the SIDkick pico is configured to. ;)

**Comment by frntc** [comment]
Will have a look in the next days...

**Comment by frntc** [comment]
fixed in v0.13

**Comment by Braincell1973** [comment]
Nope , Shadowfire still broken........

**Comment by frntc** [comment]
v0.14
