### ISSUE TITLE
Menu Corruption In Hardware Version TWO NTSC

### ISSUE THREAD

**Issue by c64manguy** [frntc/SIDKick-pico#59]
I just got my new hardware version 2 boards in and built some. I am getting the same kind of corruption in the built in menu if I change to SID type to 6581. I have attached a picture for reference. This is on one of the clone boards from China. The one with the RGB LED. I tried with the RGB firmware and just the regular PWM firmware. Both displayed the same issue. This is an NTSC C64.
![Sidkick_V2_FW202_Menu_1](https://github.com/frntc/SIDKick-pico/assets/125417812/c5d2a9e1-b643-4431-ab78-c02e129e3847)

**Comment by frntc** [comment]
It's a firmware thing, please don't open new threads for the same issue!
