### ISSUE TITLE
Audio "bumps" when all voices (three audio channels) become silent for a while, then an audio channel resume to play aidio

### ISSUE THREAD

**Issue by ZorroDJ** [frntc/SIDKick-pico#63]
I've tested all the possible settings, but it appears that a sort of "squelch" without a proper zero-crossing or DC-bias problem exists when emulated SID pass from no audio to some audio (tested with Mario Bros C64 port & Mojo Demo).
This causes a intelligible "bumb" on my speakers every time. Original sid is ok. Tested with PWM with no D/A.

**Comment by frntc** [comment]
Yes, this is known (I implemented this to avoid a "click" when PWM is initialized and then used). Will be fixed at some point. It's not present in the DAC-output.

**Comment by frntc** [comment]
This problem (except for an unavoidable small click on reset) should be gone with the updated firmware.
