### ISSUE TITLE
100kr resistor option on 0.2 revision board

### ISSUE THREAD

**Issue by Teams02** [frntc/SIDKick-pico#69]
Hi bud. 

Loving the sidkick pico. Finally get to listen to 2sid sids :). 

I'm building a pwm optional dac board for a friends c64.

I've soldered everything on apart from a 100kr resistor that's not in the BOM list and has an opt underneath it

I've probably missed something but is the resistor required?.

**Comment by frntc** [comment]
In all my tests it was not required. If necessary a 10kR (or any large resistance) should do the job.
