### ISSUE TITLE
Hard reset solder jumper

### ISSUE THREAD

**Issue by repetto74** [frntc/SIDKick-pico#71]
Hello,

Could we better understand what is the purpose of the tiny solder jumper pad for the "hard reset"? 
When should we close this jumper with a blob of solder?

Thanks
Riccardo

**Comment by frntc** [comment]
Never :-) I just kept it as a fail-safe option... if closed, the RP2040 is reset when the C64 is reset, but that's not necessary.

**Comment by repetto74** [comment]
Ok got it, thanks a lot for the clarification 😄
