### ISSUE TITLE
Audio from DAC external module - no sound

### ISSUE THREAD

**Issue by repetto74** [frntc/SIDKick-pico#72]
Hello,

I have the Sidkick pcb 0.20 with the external audio DAC module PMC5102. I programmed the Pico with the 0.2 firmware SKpico2_DAC_PWM_LED.uf2. I have tested the Sidkick Pico without connecting any extra line for stereo output.
I do have sound coming out from the video/audio port of the C64 so PWM is fine. Unfortunately when I hook the audio jack to the audio jack connector of the PMC5102 I just get no sound. I would like to understand what I am doing wrong.

- Do I need to upload another firmware (only DAC?)
- Do I need to set any jumper on the PCM5102? As far as I understood those solder jumper can be left untouched by default.
- Do I need to connect the extra lines (A5/A8) for stereo in order to have the DAC output working?

The DAC red power light is illuminated.

Another weird thing I noticed during my test. The SIDPico generate a kind of hissing sound briefly for 1 second when switching on the C64. I noticed that this hissing sound stays permanently in the background when audio is generated. As an example when loading a game like either Lazy Jones or Ghostbusters, I do hear this hissing sound permanently in the background while it is supposed to stop once the Sid pico is initialized right?

Many thanks.
Riccardo

**Comment by frntc** [comment]
The firmware is good. Have you checked https://github.com/frntc/SIDKick-pico#audio-output ? You don't need to connect A5/A8 for using the DAC output

**Comment by repetto74** [comment]
Yes, I checked the Audio Output section and missed apparently the four solder jumpers on the DAC picture which have been closed :-). Should be this the issue :-).

**Comment by repetto74** [comment]
Set solder jumpers accordingly and all is good now from the DAC :-). Fixed also the background tone, it was a bridge between one end of a resistor and a pin on the Pico. Thanks!

**Comment by repetto74** [comment]
Solved
