### ISSUE TITLE
Aisler link?

### ISSUE THREAD

**Issue by shred** [frntc/SIDKick-pico#73]
Can you also provide an Aisler link? I'm not a big fan of PCBway and would rather support an European board manufacturer.

Thank you!

**Comment by frntc** [comment]
I get you point, but to be honest, I have no experience with Aisler. Do they offer a similar service (order PCBs from someone else design)?

(However, I have to say that I don't have the time at the moment, nor do I feel like ordering more test batches to ensure that all production data which I offer is correct -- without testing I would not want to do that)

**Comment by shred** [comment]
All I know is that you can create a private link to your uploaded project there that you could share. Everyone knowing that link would be able to order boards at Aisler. But there is no public and searchable community website like at PCBway.

I was asking because the Restore Store has no SIDkick-picos on stock anymore, and it's unclear when (or if) they will be on stock again.

**Comment by Piligrim-77** [comment]
Hi, I really like this project, thanks to the author. I'd like to get Gerber files too. Unfortunately, the PCBWay website is blocked in my country and it is impossible to order anything on it. Is there any other way to buy Gerber? For example, transfer payment to PayPal and receive files by email or other options?...

**Comment by frntc** [comment]
@shred : I'm sure Restore Store will have SKpicos again soon (likely also the new variant)

@Piligrim-77 : sorry, but I had bad experiences with making Gerbers for my other projects available (people violating the HW-licenses, selling for profit on ebay and other platforms -- I don't want to insinuate anything here!) and thus I decided to not share them at the moment.

**Comment by shred** [comment]
Thank you! Then I will wait for the Restore Store.
