### ISSUE TITLE
Pico don't save settings and corruption issue

### ISSUE THREAD

**Issue by Pinks64** [frntc/SIDKick-pico#90]
Hi I just bought and assembly Sidkick pico from 
https://restore-store.de/home/687-sidkick-pico-v02-2024-frenetic-4000000006879.html I also buy DAC but for now I'm not using it. My problem is that pico don't save settings and sometimes with some settings music is garbled. Also when I play test music from pico it's loud even sliders are on minimum/off position, after I change Sid there is no sound but after moving slider it works. Also now don't know why when I change Sid boost music is playing without interruption, earlier there was small interruption after each change. My mainboard is 250469 no. 252311 rev.b on other mainboard I have the same issue both pal.
![IMG_20241102_134712](https://github.com/user-attachments/assets/5ab08307-f1f5-48e5-9de2-7f9119d86dd3)
![IMG_20241102_134656](https://github.com/user-attachments/assets/fde6e508-1493-4502-ba22-ee482e9c812b)
![IMG_20241102_134220](https://github.com/user-attachments/assets/22ee727d-3ba4-4f5b-b26b-5bedc0eaa401)
![IMG_20241102_134208](https://github.com/user-attachments/assets/63bcf39c-0006-4fc4-8e85-7162bc316827)

This project is awesome, probably i just buy another kit and tray again or buy official pico and see.

**Comment by frntc** [comment]
The configuration menu looks pretty weird. Have you tried different timings? Maybe the self-diag doesn't catch that one. See https://github.com/frntc/SIDKick-pico#troubleshooting

Testing with a different Pico is also a good idea, the black clones sometimes have quality issues.

**Comment by Pinks64** [comment]
> The configuration menu looks pretty weird. Have you tried different timings? Maybe the self-diag doesn't catch that one. See https://github.com/frntc/SIDKick-pico#troubleshooting
> 
> Testing with a different Pico is also a good idea, the black clones sometimes have quality issues.

Thank you for replay, I will check this SKpicotiming tool as it can be run on C64 and I don't have knowledge of scripts :( also just recall that I have some dead test cartridge without harness and check that also. Yesterday I ordered official pi pico so 2-3 day and also check that one. Mouse works fine as I can tell.

Apologize for my English and again thank you for your time and project.

**Comment by Pinks64** [comment]
> The configuration menu looks pretty weird. Have you tried different timings? Maybe the self-diag doesn't catch that one. See https://github.com/frntc/SIDKick-pico#troubleshooting
> 
> Testing with a different Pico is also a good idea, the black clones sometimes have quality issues.

Hello :) I have changed to official pico and now it save settings and show firmware :) 
I still have some glitches but there is another topic for this issue.
![IMG_20241116_160330](https://github.com/user-attachments/assets/4e59f2c8-75ed-422b-b3b6-01ecef3f4ea4)
![IMG_20241116_160348](https://github.com/user-attachments/assets/ea759267-1f35-4d79-96ac-3a59701fbae8)
![IMG_20241116_160358](https://github.com/user-attachments/assets/a352e225-1d37-4250-b934-0eb05e7fd75a)
![IMG_20241116_160411](https://github.com/user-attachments/assets/812f0500-ba58-4e4c-8773-0772d0d5bc25)

**Comment by frntc** [comment]
The moved "pico" sprite and "A568IO" are just showing mouse activity (none attached) and detected additional address lines (if you meant this with glitches)
